import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import DefaultProvider from "@/contexts/default/defaultProvider";
import Header from "@/components/header/header";

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "T-Shirt & Mugs",
  description: "Generated by Jessica Aguiar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DefaultProvider>
      <html lang="en">
        <body className={saira.className}>
          <Header />
          {children}
        </body>
      </html>
    </DefaultProvider>
  );
}
